version: '3'
services:
  web:
    # Replace <YOUR_GITHUB_USERNAME> with your actual GitHub username or organization
    image: ghcr.io/tomkoooo/oac:latest
    ports:
      - "6070:3000"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http web:3000 --log=stdout
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - web
