version: '3'
services:
  oac:
    image: ghcr.io/tomkoooo/oac:main
    container_name: oac
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - mongo_default
      - tdarts_default
      - ix-nginx-proxy-manager_default

networks:
  mongo_default:
    external: true
  tdarts_default:
    external: false
  ix-nginx-proxy-manager_default:
    external: true
